// gen_bool_cols extracts all column names typed boolean in the Fleet PG baseline
// schema and writes a generated Go source file to server/platform/postgres/.
// Run via: go run ./tools/pgcompat/gen_bool_cols
// Or via: go generate ./server/platform/postgres/...
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strings"

	"github.com/fleetdm/fleet/v4/tools/pgcompat/internal/allowlist"
)

var reBoolCol = regexp.MustCompile(`^\s+([a-z][a-z0-9_]*)\s+boolean\b`)

func main() {
	schemaPath := flag.String("schema", "server/datastore/mysql/pg_baseline_schema.sql", "path to PG baseline schema")
	outPath := flag.String("output", "server/platform/postgres/schema_bool_cols_gen.go", "path to write generated file")
	splitsPath := flag.String("splits", "tools/pgcompat/known_bool_col_splits.txt", "path to known bool/smallint split names to exclude")
	flag.Parse()

	// Split-typed names (boolean in one table, smallint in another) must not
	// enter the generic name-keyed bool machinery: the smallint side would be
	// mis-rewritten (awaiting_configuration's tri-state collapse broke the
	// Windows ESP state machine). check_bool_col_split guards the list.
	splitNames, err := allowlist.LoadLines(*splitsPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read %s: %v\n", *splitsPath, err)
		os.Exit(1)
	}

	f, err := os.Open(*schemaPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "open %s: %v\n", *schemaPath, err)
		os.Exit(1)
	}

	seen := map[string]bool{}
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		if m := reBoolCol.FindStringSubmatch(scanner.Text()); m != nil {
			if !splitNames[m[1]] {
				seen[m[1]] = true
			}
		}
	}
	scanErr := scanner.Err()
	f.Close()
	if scanErr != nil {
		fmt.Fprintf(os.Stderr, "scan: %v\n", scanErr)
		os.Exit(1)
	}

	cols := make([]string, 0, len(seen))
	for col := range seen {
		cols = append(cols, col)
	}
	sort.Strings(cols)

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by tools/pgcompat/gen_bool_cols; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package postgres\n\n")
	fmt.Fprintf(&buf, "// schemaBoolCols contains every column name typed boolean in the Fleet PG\n")
	fmt.Fprintf(&buf, "// baseline schema (pg_baseline_schema.sql). Used by rebind_driver.go to\n")
	fmt.Fprintf(&buf, "// rewrite MySQL boolean integer literals (= 1, = 0) to PG boolean literals.\n")
	fmt.Fprintf(&buf, "// Regenerate with: go run ./tools/pgcompat/gen_bool_cols\n")
	fmt.Fprintf(&buf, "var schemaBoolCols = []string{\n")
	for _, col := range cols {
		fmt.Fprintf(&buf, "\t%q,\n", col)
	}
	fmt.Fprintf(&buf, "}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(*outPath, src, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", *outPath, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s with %d boolean columns:\n", *outPath, len(cols))
	for _, col := range cols {
		fmt.Printf("  %s\n", col)
	}

	// Warn if any hand-curated unqualified entries are missing from schema —
	// indicates schema divergence or a column that was never actually boolean.
	handCurated := []string{
		"active", "canceled", "discard_data", "enabled", "encrypted",
		"enrolled", "global_stats", "install_during_setup", "installed_from_dep",
		"is_kernel", "is_personal_enrollment", "is_server",
		"needs_full_membership_cleanup", "refetch_requested", "resync",
		"revoked", "saved", "self_service", "skipped", "sync_request",
		"terms_expired", "uninstall",
	}
	var missing []string
	for _, col := range handCurated {
		if !seen[col] {
			missing = append(missing, col)
		}
	}
	if len(missing) > 0 {
		fmt.Fprintf(os.Stderr, "WARNING: %d previously hand-curated columns not found in schema: %s\n",
			len(missing), strings.Join(missing, ", "))
	}
}
