-- Generated by tools/pg-index-translate. DO NOT EDIT BY HAND.
-- Source: server/datastore/mysql/schema.sql
-- Translates every MySQL KEY / UNIQUE KEY clause to a PG CREATE INDEX.
-- IF NOT EXISTS makes the migration idempotent / safe to re-run.


-- abm_tokens
CREATE INDEX IF NOT EXISTS fk_abm_tokens_ios_default_team_id ON abm_tokens (ios_default_team_id);
CREATE INDEX IF NOT EXISTS fk_abm_tokens_ipados_default_team_id ON abm_tokens (ipados_default_team_id);
CREATE INDEX IF NOT EXISTS fk_abm_tokens_macos_default_team_id ON abm_tokens (macos_default_team_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_abm_tokens_organization_name ON abm_tokens (organization_name);

-- acme_accounts
CREATE UNIQUE INDEX IF NOT EXISTS idx_enrollment_id_thumbprint ON acme_accounts (acme_enrollment_id, json_web_key_thumbprint);

-- acme_authorizations
CREATE INDEX IF NOT EXISTS acme_order_id ON acme_authorizations (acme_order_id);

-- acme_challenges
CREATE INDEX IF NOT EXISTS acme_authorization_id ON acme_challenges (acme_authorization_id);

-- acme_enrollments
CREATE UNIQUE INDEX IF NOT EXISTS idx_path_identifier ON acme_enrollments (path_identifier);

-- acme_orders
CREATE INDEX IF NOT EXISTS acme_account_id ON acme_orders (acme_account_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_issued_certificate_serial ON acme_orders (issued_certificate_serial);

-- activity_host_past
CREATE INDEX IF NOT EXISTS fk_host_activities_activity_id ON activity_host_past (activity_id);

-- activity_past
CREATE INDEX IF NOT EXISTS activities_created_at_idx ON activity_past (created_at);
CREATE INDEX IF NOT EXISTS activities_streamed_idx ON activity_past (streamed);
CREATE INDEX IF NOT EXISTS fk_activities_user_id ON activity_past (user_id);
CREATE INDEX IF NOT EXISTS idx_activities_activity_type ON activity_past (activity_type);
CREATE INDEX IF NOT EXISTS idx_activities_type_created ON activity_past (activity_type, created_at);
CREATE INDEX IF NOT EXISTS idx_activities_user_email ON activity_past (user_email);
CREATE INDEX IF NOT EXISTS idx_activities_user_name ON activity_past (user_name);

-- aggregated_stats
CREATE INDEX IF NOT EXISTS aggregated_stats_type_idx ON aggregated_stats (type);
CREATE INDEX IF NOT EXISTS idx_aggregated_stats_updated_at ON aggregated_stats (updated_at);

-- android_app_configurations
CREATE UNIQUE INDEX IF NOT EXISTS idx_global_or_team_id_application_id ON android_app_configurations (global_or_team_id, application_id);
CREATE INDEX IF NOT EXISTS team_id ON android_app_configurations (team_id);

-- android_devices
CREATE UNIQUE INDEX IF NOT EXISTS idx_android_devices_device_id ON android_devices (device_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_android_devices_enterprise_specific_id ON android_devices (enterprise_specific_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_android_devices_host_id ON android_devices (host_id);

-- batch_activities
CREATE INDEX IF NOT EXISTS batch_script_executions_script_id ON batch_activities (script_id);
CREATE INDEX IF NOT EXISTS idx_batch_activities_status ON batch_activities (status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_batch_script_executions_execution_id ON batch_activities (execution_id);

-- batch_activity_host_results
CREATE INDEX IF NOT EXISTS idx_batch_script_execution_host_result_execution_id ON batch_activity_host_results (batch_execution_id);
CREATE UNIQUE INDEX IF NOT EXISTS unique_batch_host_results_execution_hostid ON batch_activity_host_results (batch_execution_id, host_id);

-- ca_config_assets
CREATE UNIQUE INDEX IF NOT EXISTS idx_ca_config_assets_name ON ca_config_assets (name);

-- calendar_events
CREATE UNIQUE INDEX IF NOT EXISTS idx_calendar_events_uuid_bin_unique ON calendar_events (uuid_bin);
CREATE UNIQUE INDEX IF NOT EXISTS idx_one_calendar_event_per_email ON calendar_events (email);

-- carve_metadata
CREATE INDEX IF NOT EXISTS host_id ON carve_metadata (host_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_name ON carve_metadata (name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_session_id ON carve_metadata (session_id);

-- certificate_authorities
CREATE UNIQUE INDEX IF NOT EXISTS idx_ca_type_name ON certificate_authorities (type, name);

-- certificate_templates
CREATE INDEX IF NOT EXISTS certificate_authority_id ON certificate_templates (certificate_authority_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_cert_team_name ON certificate_templates (team_id, name);

-- conditional_access_scep_certificates
CREATE INDEX IF NOT EXISTS idx_conditional_access_host_id ON conditional_access_scep_certificates (host_id);

-- cron_stats
CREATE INDEX IF NOT EXISTS idx_cron_stats_name_created_at ON cron_stats (name, created_at);

-- default_team_config_json
CREATE UNIQUE INDEX IF NOT EXISTS id ON default_team_config_json (id);

-- distributed_query_campaign_targets
CREATE INDEX IF NOT EXISTS idx_distributed_query_campaign_targets_campaign_id ON distributed_query_campaign_targets (distributed_query_campaign_id);

-- email_changes
CREATE INDEX IF NOT EXISTS fk_email_changes_users ON email_changes (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_email_changes_token ON email_changes (token);

-- enroll_secrets
CREATE INDEX IF NOT EXISTS fk_enroll_secrets_team_id ON enroll_secrets (team_id);

-- fleet_maintained_apps
CREATE UNIQUE INDEX IF NOT EXISTS idx_fleet_library_apps_token ON fleet_maintained_apps (slug);

-- fleet_variables
CREATE UNIQUE INDEX IF NOT EXISTS idx_fleet_variables_name_is_prefix ON fleet_variables (name, is_prefix);

-- host_batteries
CREATE UNIQUE INDEX IF NOT EXISTS idx_host_batteries_host_id_serial_number ON host_batteries (host_id, serial_number);

-- host_calendar_events
CREATE INDEX IF NOT EXISTS calendar_event_id ON host_calendar_events (calendar_event_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_one_calendar_event_per_host ON host_calendar_events (host_id);

-- host_certificate_sources
CREATE UNIQUE INDEX IF NOT EXISTS idx_host_certificate_sources_unique ON host_certificate_sources (host_certificate_id, source, username);

-- host_certificate_templates
CREATE INDEX IF NOT EXISTS fk_host_certificate_templates_operation_type ON host_certificate_templates (operation_type);
CREATE UNIQUE INDEX IF NOT EXISTS idx_host_certificate_templates_host_template ON host_certificate_templates (host_uuid, certificate_template_id);
CREATE INDEX IF NOT EXISTS idx_host_certificate_templates_not_valid_after ON host_certificate_templates (not_valid_after);

-- host_certificates
CREATE INDEX IF NOT EXISTS idx_host_certs_hid_cn ON host_certificates (host_id, common_name);
CREATE INDEX IF NOT EXISTS idx_host_certs_not_valid_after ON host_certificates (host_id, not_valid_after);

-- host_conditional_access
CREATE UNIQUE INDEX IF NOT EXISTS idx_host_conditional_access_host_id ON host_conditional_access (host_id);

-- host_dep_assignments
CREATE INDEX IF NOT EXISTS fk_host_dep_assignments_abm_token_id ON host_dep_assignments (abm_token_id);
CREATE INDEX IF NOT EXISTS idx_hdep_hardware_serial ON host_dep_assignments (hardware_serial);
CREATE INDEX IF NOT EXISTS idx_hdep_response ON host_dep_assignments (assign_profile_response, response_updated_at);

-- host_device_auth
CREATE INDEX IF NOT EXISTS idx_host_device_auth_previous_token ON host_device_auth (previous_token);
CREATE UNIQUE INDEX IF NOT EXISTS idx_host_device_auth_token ON host_device_auth (token);

-- host_disk_encryption_keys
CREATE INDEX IF NOT EXISTS idx_host_disk_encryption_keys_decryptable ON host_disk_encryption_keys (decryptable);

-- host_disk_encryption_keys_archive
CREATE INDEX IF NOT EXISTS idx_host_disk_encryption_keys_archive_host_created_at ON host_disk_encryption_keys_archive (host_id, created_at DESC);

-- host_disks
CREATE INDEX IF NOT EXISTS idx_host_disks_gigs_disk_space_available ON host_disks (gigs_disk_space_available);

-- host_display_names
CREATE INDEX IF NOT EXISTS display_name ON host_display_names (display_name);

-- host_emails
CREATE INDEX IF NOT EXISTS idx_host_emails_email ON host_emails (email);
CREATE INDEX IF NOT EXISTS idx_host_emails_host_id_email ON host_emails (host_id, email);

-- host_identity_scep_certificates
CREATE INDEX IF NOT EXISTS idx_host_id_scep_host_id ON host_identity_scep_certificates (host_id);
CREATE INDEX IF NOT EXISTS idx_host_id_scep_name ON host_identity_scep_certificates (name);

-- host_in_house_software_installs
CREATE INDEX IF NOT EXISTS fk_host_in_house_software_installs_in_house_app_id ON host_in_house_software_installs (in_house_app_id);
CREATE INDEX IF NOT EXISTS fk_host_in_house_software_installs_user_id ON host_in_house_software_installs (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_host_in_house_software_installs_command_uuid ON host_in_house_software_installs (command_uuid);

-- host_issues
CREATE INDEX IF NOT EXISTS total_issues_count ON host_issues (total_issues_count);

-- host_managed_local_account_passwords
CREATE INDEX IF NOT EXISTS fk_hmlap_status ON host_managed_local_account_passwords (status);
CREATE INDEX IF NOT EXISTS idx_hmlap_auto_rotate_at ON host_managed_local_account_passwords (auto_rotate_at);
CREATE INDEX IF NOT EXISTS idx_hmlap_command_uuid ON host_managed_local_account_passwords (command_uuid);

-- host_mdm
CREATE INDEX IF NOT EXISTS host_mdm_enrolled_installed_from_dep_is_personal_enrollment_idx ON host_mdm (enrolled, installed_from_dep, is_personal_enrollment);
CREATE INDEX IF NOT EXISTS host_mdm_mdm_id_idx ON host_mdm (mdm_id);

-- host_mdm_android_profiles
CREATE INDEX IF NOT EXISTS device_request_uuid ON host_mdm_android_profiles (device_request_uuid);
CREATE INDEX IF NOT EXISTS operation_type ON host_mdm_android_profiles (operation_type);
CREATE INDEX IF NOT EXISTS policy_request_uuid ON host_mdm_android_profiles (policy_request_uuid);
CREATE INDEX IF NOT EXISTS status ON host_mdm_android_profiles (status);

-- host_mdm_apple_bootstrap_packages
CREATE INDEX IF NOT EXISTS command_uuid ON host_mdm_apple_bootstrap_packages (command_uuid);

-- host_mdm_apple_declarations
CREATE INDEX IF NOT EXISTS idx_token ON host_mdm_apple_declarations (token);
CREATE INDEX IF NOT EXISTS operation_type ON host_mdm_apple_declarations (operation_type);
CREATE INDEX IF NOT EXISTS status ON host_mdm_apple_declarations (status);

-- host_mdm_apple_profiles
CREATE INDEX IF NOT EXISTS operation_type ON host_mdm_apple_profiles (operation_type);
CREATE INDEX IF NOT EXISTS status ON host_mdm_apple_profiles (status);

-- host_mdm_idp_accounts
CREATE UNIQUE INDEX IF NOT EXISTS idx_host_mdm_idp_accounts ON host_mdm_idp_accounts (host_uuid);

-- host_mdm_windows_profiles
CREATE INDEX IF NOT EXISTS operation_type ON host_mdm_windows_profiles (operation_type);
CREATE INDEX IF NOT EXISTS status ON host_mdm_windows_profiles (status);

-- host_operating_system
CREATE INDEX IF NOT EXISTS idx_host_operating_system_id ON host_operating_system (os_id);

-- host_orbit_info
CREATE INDEX IF NOT EXISTS idx_host_orbit_info_version ON host_orbit_info (version);

-- host_recovery_key_passwords
CREATE INDEX IF NOT EXISTS deleted ON host_recovery_key_passwords (deleted);
CREATE INDEX IF NOT EXISTS idx_auto_rotate_at ON host_recovery_key_passwords (auto_rotate_at);
CREATE INDEX IF NOT EXISTS operation_type ON host_recovery_key_passwords (operation_type);
CREATE INDEX IF NOT EXISTS status ON host_recovery_key_passwords (status);

-- host_scd_data
CREATE INDEX IF NOT EXISTS idx_dataset_range ON host_scd_data (dataset, valid_from, valid_to);
CREATE INDEX IF NOT EXISTS idx_valid_to_dataset ON host_scd_data (valid_to, dataset, entity_id);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_entity_bucket ON host_scd_data (dataset, entity_id, valid_from);

-- host_scim_user
CREATE INDEX IF NOT EXISTS fk_host_scim_scim_user_id ON host_scim_user (scim_user_id);

-- host_script_results
CREATE INDEX IF NOT EXISTS fk_host_script_results_script_id ON host_script_results (script_id);
CREATE INDEX IF NOT EXISTS fk_host_script_results_setup_experience_id ON host_script_results (setup_experience_script_id);
CREATE INDEX IF NOT EXISTS fk_host_script_results_user_id ON host_script_results (user_id);
CREATE INDEX IF NOT EXISTS fk_script_result_policy_id ON host_script_results (policy_id);
CREATE INDEX IF NOT EXISTS idx_host_script_canceled_created_at ON host_script_results (host_id, script_id, canceled, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_host_script_results_execution_id ON host_script_results (execution_id);
CREATE INDEX IF NOT EXISTS idx_host_script_results_host_exit_created ON host_script_results (host_id, exit_code, created_at);
CREATE INDEX IF NOT EXISTS idx_host_script_results_host_policy ON host_script_results (host_id, policy_id);
CREATE INDEX IF NOT EXISTS script_content_id ON host_script_results (script_content_id);

-- host_seen_times
CREATE INDEX IF NOT EXISTS idx_host_seen_times_seen_time ON host_seen_times (seen_time);

-- host_software
CREATE INDEX IF NOT EXISTS idx_host_software_software_id ON host_software (software_id);

-- host_software_installed_paths
CREATE INDEX IF NOT EXISTS host_id_software_id_idx ON host_software_installed_paths (host_id, software_id);

-- host_software_installs
CREATE INDEX IF NOT EXISTS fk_host_software_installs_installer_id ON host_software_installs (software_installer_id);
CREATE INDEX IF NOT EXISTS fk_host_software_installs_software_title_id ON host_software_installs (software_title_id);
CREATE INDEX IF NOT EXISTS fk_host_software_installs_user_id ON host_software_installs (user_id);
CREATE INDEX IF NOT EXISTS fk_software_install_policy_id ON host_software_installs (policy_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_host_software_installs_execution_id ON host_software_installs (execution_id);
CREATE INDEX IF NOT EXISTS idx_host_software_installs_host_installer ON host_software_installs (host_id, software_installer_id);
CREATE INDEX IF NOT EXISTS idx_host_software_installs_host_policy ON host_software_installs (host_id, policy_id);

-- host_vpp_software_installs
CREATE INDEX IF NOT EXISTS adam_id ON host_vpp_software_installs (adam_id, platform);
CREATE INDEX IF NOT EXISTS fk_host_vpp_software_installs_policy_id ON host_vpp_software_installs (policy_id);
CREATE INDEX IF NOT EXISTS fk_host_vpp_software_installs_vpp_token_id ON host_vpp_software_installs (vpp_token_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_host_vpp_software_installs_command_uuid ON host_vpp_software_installs (command_uuid);
CREATE INDEX IF NOT EXISTS user_id ON host_vpp_software_installs (user_id);

-- hosts
CREATE INDEX IF NOT EXISTS fk_hosts_team_id ON hosts (team_id);
CREATE INDEX IF NOT EXISTS hosts_platform_idx ON hosts (platform);
CREATE UNIQUE INDEX IF NOT EXISTS idx_host_unique_nodekey ON hosts (node_key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_host_unique_orbitnodekey ON hosts (orbit_node_key);
CREATE INDEX IF NOT EXISTS idx_hosts_hardware_serial ON hosts (hardware_serial);
CREATE INDEX IF NOT EXISTS idx_hosts_hostname ON hosts (hostname);
CREATE INDEX IF NOT EXISTS idx_hosts_uuid ON hosts (uuid);
CREATE UNIQUE INDEX IF NOT EXISTS idx_osquery_host_id ON hosts (osquery_host_id);

-- in_house_app_configurations
CREATE UNIQUE INDEX IF NOT EXISTS idx_in_house_app_config_app ON in_house_app_configurations (in_house_app_id);

-- in_house_app_labels
CREATE UNIQUE INDEX IF NOT EXISTS id_in_house_app_labels_in_house_app_id_label_id ON in_house_app_labels (in_house_app_id, label_id);
CREATE INDEX IF NOT EXISTS label_id ON in_house_app_labels (label_id);

-- in_house_app_software_categories
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_in_house_app_id_software_category_id ON in_house_app_software_categories (in_house_app_id, software_category_id);
CREATE INDEX IF NOT EXISTS in_house_app_software_categories_ibfk_2 ON in_house_app_software_categories (software_category_id);

-- in_house_app_upcoming_activities
CREATE INDEX IF NOT EXISTS fk_in_house_app_upcoming_activities_in_house_app_id ON in_house_app_upcoming_activities (in_house_app_id);
CREATE INDEX IF NOT EXISTS fk_in_house_app_upcoming_activities_software_title_id ON in_house_app_upcoming_activities (software_title_id);

-- in_house_apps
CREATE INDEX IF NOT EXISTS fk_in_house_apps_title ON in_house_apps (title_id);
CREATE UNIQUE INDEX IF NOT EXISTS global_or_team_id ON in_house_apps (global_or_team_id, filename, platform);

-- invite_teams
CREATE INDEX IF NOT EXISTS fk_team_id ON invite_teams (team_id);

-- invites
CREATE UNIQUE INDEX IF NOT EXISTS idx_invite_unique_email ON invites (email);
CREATE UNIQUE INDEX IF NOT EXISTS idx_invite_unique_key ON invites (token);

-- jobs
CREATE INDEX IF NOT EXISTS idx_jobs_name_state ON jobs (name, state);
CREATE INDEX IF NOT EXISTS idx_jobs_state_not_before_updated_at ON jobs (state, not_before, updated_at);

-- kernel_host_counts
CREATE INDEX IF NOT EXISTS idx_kernel_host_counts_os_version_software ON kernel_host_counts (os_version_id, software_id, hosts_count);
CREATE UNIQUE INDEX IF NOT EXISTS idx_kernels_unique_mapping ON kernel_host_counts (os_version_id, team_id, software_id);
CREATE INDEX IF NOT EXISTS software_title_id ON kernel_host_counts (software_title_id);

-- label_membership
CREATE INDEX IF NOT EXISTS idx_lm_label_id ON label_membership (label_id);

-- labels
CREATE INDEX IF NOT EXISTS author_id ON labels (author_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_label_unique_name ON labels (name);
CREATE INDEX IF NOT EXISTS team_id ON labels (team_id);

-- legacy_host_mdm_enroll_refs
CREATE INDEX IF NOT EXISTS idx_legacy_enroll_refs_host_uuid ON legacy_host_mdm_enroll_refs (host_uuid);

-- locks
CREATE UNIQUE INDEX IF NOT EXISTS idx_name ON locks (name);

-- mdm_android_configuration_profiles
CREATE UNIQUE INDEX IF NOT EXISTS auto_increment ON mdm_android_configuration_profiles (auto_increment);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mdm_android_configuration_profiles_team_id_name ON mdm_android_configuration_profiles (team_id, name);

-- mdm_apple_bootstrap_packages
CREATE UNIQUE INDEX IF NOT EXISTS idx_token ON mdm_apple_bootstrap_packages (token);

-- mdm_apple_configuration_profiles
CREATE UNIQUE INDEX IF NOT EXISTS idx_mdm_apple_config_prof_id ON mdm_apple_configuration_profiles (profile_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mdm_apple_config_prof_team_identifier ON mdm_apple_configuration_profiles (team_id, identifier);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mdm_apple_config_prof_team_name ON mdm_apple_configuration_profiles (team_id, name);

-- mdm_apple_declaration_activation_references
CREATE INDEX IF NOT EXISTS reference ON mdm_apple_declaration_activation_references (reference);

-- mdm_apple_declarations
CREATE UNIQUE INDEX IF NOT EXISTS auto_increment ON mdm_apple_declarations (auto_increment);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mdm_apple_declaration_team_identifier ON mdm_apple_declarations (team_id, identifier);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mdm_apple_declaration_team_name ON mdm_apple_declarations (team_id, name);

-- mdm_apple_declarative_requests
CREATE INDEX IF NOT EXISTS mdm_apple_declarative_requests_enrollment_id ON mdm_apple_declarative_requests (enrollment_id);

-- mdm_apple_default_setup_assistants
CREATE INDEX IF NOT EXISTS fk_mdm_default_setup_assistant_abm_token_id ON mdm_apple_default_setup_assistants (abm_token_id);
CREATE INDEX IF NOT EXISTS fk_mdm_default_setup_assistant_team_id ON mdm_apple_default_setup_assistants (team_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mdm_default_setup_assistant_global_or_team_id_abm_token_id ON mdm_apple_default_setup_assistants (global_or_team_id, abm_token_id);

-- mdm_apple_enrollment_profiles
CREATE UNIQUE INDEX IF NOT EXISTS idx_token ON mdm_apple_enrollment_profiles (token);
CREATE UNIQUE INDEX IF NOT EXISTS idx_type ON mdm_apple_enrollment_profiles (type);

-- mdm_apple_setup_assistant_profiles
CREATE INDEX IF NOT EXISTS fk_mdm_apple_setup_assistant_profiles_abm_token_id ON mdm_apple_setup_assistant_profiles (abm_token_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mdm_apple_setup_assistant_profiles_asst_id_tok_id ON mdm_apple_setup_assistant_profiles (setup_assistant_id, abm_token_id);

-- mdm_apple_setup_assistants
CREATE INDEX IF NOT EXISTS fk_mdm_setup_assistant_team_id ON mdm_apple_setup_assistants (team_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mdm_setup_assistant_global_or_team_id ON mdm_apple_setup_assistants (global_or_team_id);

-- mdm_config_assets
CREATE UNIQUE INDEX IF NOT EXISTS idx_mdm_config_assets_name_deletion_uuid ON mdm_config_assets (name, deletion_uuid);

-- mdm_configuration_profile_labels
CREATE UNIQUE INDEX IF NOT EXISTS idx_mdm_configuration_profile_labels_android_label_name ON mdm_configuration_profile_labels (android_profile_uuid, label_name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mdm_configuration_profile_labels_apple_label_name ON mdm_configuration_profile_labels (apple_profile_uuid, label_name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mdm_configuration_profile_labels_windows_label_name ON mdm_configuration_profile_labels (windows_profile_uuid, label_name);
CREATE INDEX IF NOT EXISTS label_id ON mdm_configuration_profile_labels (label_id);

-- mdm_configuration_profile_variables
CREATE UNIQUE INDEX IF NOT EXISTS idx_mdm_config_profile_vars_apple_decl_variable ON mdm_configuration_profile_variables (apple_declaration_uuid, fleet_variable_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mdm_configuration_profile_variables_apple_variable ON mdm_configuration_profile_variables (apple_profile_uuid, fleet_variable_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mdm_configuration_profile_variables_windows_label_name ON mdm_configuration_profile_variables (windows_profile_uuid, fleet_variable_id);
CREATE INDEX IF NOT EXISTS mdm_configuration_profile_variables_fleet_variable_id ON mdm_configuration_profile_variables (fleet_variable_id);

-- mdm_declaration_labels
CREATE UNIQUE INDEX IF NOT EXISTS idx_mdm_declaration_labels_label_name ON mdm_declaration_labels (apple_declaration_uuid, label_name);
CREATE INDEX IF NOT EXISTS label_id ON mdm_declaration_labels (label_id);

-- mdm_idp_accounts
CREATE UNIQUE INDEX IF NOT EXISTS unique_idp_email ON mdm_idp_accounts (email);

-- mdm_windows_configuration_profiles
CREATE UNIQUE INDEX IF NOT EXISTS auto_increment ON mdm_windows_configuration_profiles (auto_increment);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mdm_windows_configuration_profiles_team_id_name ON mdm_windows_configuration_profiles (team_id, name);

-- mdm_windows_enrollments
CREATE INDEX IF NOT EXISTS idx_mdm_windows_enrollments_host_uuid ON mdm_windows_enrollments (host_uuid);
CREATE INDEX IF NOT EXISTS idx_mdm_windows_enrollments_mdm_device_id ON mdm_windows_enrollments (mdm_device_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_type ON mdm_windows_enrollments (mdm_hardware_id);

-- microsoft_compliance_partner_integrations
CREATE UNIQUE INDEX IF NOT EXISTS idx_microsoft_compliance_partner_tenant_id ON microsoft_compliance_partner_integrations (tenant_id);

-- mobile_device_management_solutions
CREATE UNIQUE INDEX IF NOT EXISTS idx_mobile_device_management_solutions_name ON mobile_device_management_solutions (name, server_url);

-- munki_issues
CREATE UNIQUE INDEX IF NOT EXISTS idx_munki_issues_name ON munki_issues (name, issue_type);

-- nano_cert_auth_associations
CREATE INDEX IF NOT EXISTS renew_command_uuid_fk ON nano_cert_auth_associations (renew_command_uuid);

-- nano_command_results
CREATE INDEX IF NOT EXISTS command_uuid ON nano_command_results (command_uuid);
CREATE INDEX IF NOT EXISTS idx_ncr_lookup ON nano_command_results (id, command_uuid, status);
CREATE INDEX IF NOT EXISTS status ON nano_command_results (status);

-- nano_devices
CREATE INDEX IF NOT EXISTS fk_nano_devices_team_id ON nano_devices (enroll_team_id);
CREATE INDEX IF NOT EXISTS serial_number ON nano_devices (serial_number);

-- nano_enrollment_queue
CREATE INDEX IF NOT EXISTS command_uuid ON nano_enrollment_queue (command_uuid);
CREATE INDEX IF NOT EXISTS idx_neq_filter ON nano_enrollment_queue (active, priority, created_at);
CREATE INDEX IF NOT EXISTS priority ON nano_enrollment_queue (priority DESC, created_at);

-- nano_enrollments
CREATE INDEX IF NOT EXISTS device_id ON nano_enrollments (device_id);
CREATE INDEX IF NOT EXISTS type ON nano_enrollments (type);
CREATE UNIQUE INDEX IF NOT EXISTS user_id ON nano_enrollments (user_id);

-- nano_users
CREATE INDEX IF NOT EXISTS device_id ON nano_users (device_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_id ON nano_users (id);

-- network_interfaces
CREATE INDEX IF NOT EXISTS idx_network_interfaces_hosts_fk ON network_interfaces (host_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_network_interfaces_unique_ip_host_intf ON network_interfaces (ip_address, host_id, interface);

-- operating_system_version_vulnerabilities
CREATE INDEX IF NOT EXISTS idx_os_version_vulnerabilities_os_version_team_cve ON operating_system_version_vulnerabilities (team_id, os_version_id, cve);
CREATE INDEX IF NOT EXISTS idx_os_version_vulnerabilities_updated_at ON operating_system_version_vulnerabilities (updated_at);

-- operating_system_vulnerabilities
CREATE INDEX IF NOT EXISTS idx_os_vulnerabilities_cve ON operating_system_vulnerabilities (cve);
CREATE UNIQUE INDEX IF NOT EXISTS idx_os_vulnerabilities_unq_os_id_cve ON operating_system_vulnerabilities (operating_system_id, cve);

-- operating_systems
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_os ON operating_systems (name, version, arch, kernel_version, platform, display_version, installation_type);

-- pack_targets
CREATE UNIQUE INDEX IF NOT EXISTS constraint_pack_target_unique ON pack_targets (pack_id, target_id, type);

-- packs
CREATE UNIQUE INDEX IF NOT EXISTS idx_pack_unique_name ON packs (name);

-- policies
CREATE INDEX IF NOT EXISTS fk_patch_software_title_id ON policies (patch_software_title_id);
CREATE INDEX IF NOT EXISTS fk_policies_script_id ON policies (script_id);
CREATE INDEX IF NOT EXISTS fk_policies_software_installer_id ON policies (software_installer_id);
CREATE INDEX IF NOT EXISTS fk_policies_vpp_apps_team_id ON policies (vpp_apps_teams_id);
CREATE INDEX IF NOT EXISTS idx_policies_author_id ON policies (author_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_policies_checksum ON policies (checksum);
CREATE INDEX IF NOT EXISTS idx_policies_team_id ON policies (team_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_team_id_patch_software_title_id ON policies (team_id, patch_software_title_id);

-- policy_labels
CREATE UNIQUE INDEX IF NOT EXISTS idx_policy_labels_policy_label ON policy_labels (policy_id, label_id);
CREATE INDEX IF NOT EXISTS policy_labels_label_id ON policy_labels (label_id);

-- policy_membership
CREATE INDEX IF NOT EXISTS idx_policy_membership_host_id_passes ON policy_membership (host_id, passes);
CREATE INDEX IF NOT EXISTS idx_policy_membership_passes ON policy_membership (passes);

-- policy_stats
CREATE UNIQUE INDEX IF NOT EXISTS policy_id ON policy_stats (policy_id, inherited_team_id_char);

-- queries
CREATE INDEX IF NOT EXISTS author_id ON queries (author_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_name_team_id_unq ON queries (name, team_id_char);
CREATE INDEX IF NOT EXISTS idx_queries_schedule_automations ON queries (is_scheduled, automations_enabled);
CREATE UNIQUE INDEX IF NOT EXISTS idx_team_id_name_unq ON queries (team_id_char, name);
CREATE INDEX IF NOT EXISTS idx_team_id_saved_auto_interval ON queries (team_id, saved, automations_enabled, schedule_interval);

-- query_labels
CREATE UNIQUE INDEX IF NOT EXISTS idx_query_labels_query_label ON query_labels (query_id, label_id);
CREATE INDEX IF NOT EXISTS query_labels_label_id ON query_labels (label_id);

-- query_results
CREATE INDEX IF NOT EXISTS idx_query_id_has_data_host_id_last_fetched ON query_results (query_id, has_data, host_id, last_fetched);
CREATE INDEX IF NOT EXISTS idx_query_id_host_id_last_fetched ON query_results (query_id, host_id, last_fetched);

-- scheduled_queries
CREATE INDEX IF NOT EXISTS fk_scheduled_queries_queries ON scheduled_queries (team_id_char, query_name);
CREATE INDEX IF NOT EXISTS scheduled_queries_pack_id ON scheduled_queries (pack_id);
CREATE INDEX IF NOT EXISTS scheduled_queries_query_name ON scheduled_queries (query_name);
CREATE UNIQUE INDEX IF NOT EXISTS unique_names_in_packs ON scheduled_queries (name, pack_id);

-- scheduled_query_stats
CREATE INDEX IF NOT EXISTS scheduled_query_id ON scheduled_query_stats (scheduled_query_id);

-- scim_groups
CREATE UNIQUE INDEX IF NOT EXISTS idx_scim_groups_display_name ON scim_groups (display_name);
CREATE INDEX IF NOT EXISTS idx_scim_groups_external_id ON scim_groups (external_id);

-- scim_user_emails
CREATE INDEX IF NOT EXISTS fk_scim_user_emails_scim_user_id ON scim_user_emails (scim_user_id);
CREATE INDEX IF NOT EXISTS idx_scim_user_emails_email_type ON scim_user_emails (type, email);

-- scim_user_group
CREATE INDEX IF NOT EXISTS fk_scim_user_group_group_id ON scim_user_group (group_id);

-- scim_users
CREATE INDEX IF NOT EXISTS idx_scim_users_external_id ON scim_users (external_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_scim_users_user_name ON scim_users (user_name);

-- script_contents
CREATE UNIQUE INDEX IF NOT EXISTS idx_script_contents_md5_checksum ON script_contents (md5_checksum);

-- script_upcoming_activities
CREATE INDEX IF NOT EXISTS fk_script_upcoming_activities_policy_id ON script_upcoming_activities (policy_id);
CREATE INDEX IF NOT EXISTS fk_script_upcoming_activities_script_content_id ON script_upcoming_activities (script_content_id);
CREATE INDEX IF NOT EXISTS fk_script_upcoming_activities_script_id ON script_upcoming_activities (script_id);
CREATE INDEX IF NOT EXISTS fk_script_upcoming_activities_setup_experience_script_id ON script_upcoming_activities (setup_experience_script_id);

-- scripts
CREATE UNIQUE INDEX IF NOT EXISTS idx_scripts_global_or_team_id_name ON scripts (global_or_team_id, name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_scripts_team_name ON scripts (team_id, name);
CREATE INDEX IF NOT EXISTS script_content_id ON scripts (script_content_id);

-- secret_variables
CREATE UNIQUE INDEX IF NOT EXISTS idx_secret_variables_name ON secret_variables (name);

-- sessions
CREATE UNIQUE INDEX IF NOT EXISTS idx_session_unique_key ON sessions (key);

-- setup_experience_scripts
CREATE INDEX IF NOT EXISTS fk_setup_experience_scripts_ibfk_1 ON setup_experience_scripts (team_id);
CREATE INDEX IF NOT EXISTS idx_script_content_id ON setup_experience_scripts (script_content_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_setup_experience_scripts_global_or_team_id ON setup_experience_scripts (global_or_team_id);

-- setup_experience_status_results
CREATE INDEX IF NOT EXISTS fk_setup_experience_status_results_ses_id ON setup_experience_status_results (setup_experience_script_id);
CREATE INDEX IF NOT EXISTS fk_setup_experience_status_results_si_id ON setup_experience_status_results (software_installer_id);
CREATE INDEX IF NOT EXISTS fk_setup_experience_status_results_va_id ON setup_experience_status_results (vpp_app_team_id);
CREATE INDEX IF NOT EXISTS idx_setup_experience_scripts_host_uuid ON setup_experience_status_results (host_uuid);
CREATE INDEX IF NOT EXISTS idx_setup_experience_scripts_hsi_id ON setup_experience_status_results (host_software_installs_execution_id);
CREATE INDEX IF NOT EXISTS idx_setup_experience_scripts_nano_command_uuid ON setup_experience_status_results (nano_command_uuid);
CREATE INDEX IF NOT EXISTS idx_setup_experience_scripts_script_execution_id ON setup_experience_status_results (script_execution_id);

-- software
CREATE INDEX IF NOT EXISTS idx_software_bundle_identifier ON software (bundle_identifier);
CREATE UNIQUE INDEX IF NOT EXISTS idx_software_checksum ON software (checksum);
CREATE INDEX IF NOT EXISTS idx_sw_name_source_browser ON software (name, source, extension_for);
CREATE INDEX IF NOT EXISTS software_listing_idx ON software (name);
CREATE INDEX IF NOT EXISTS software_source_vendor_idx ON software (source, vendor_old);
CREATE INDEX IF NOT EXISTS title_id ON software (title_id);

-- software_categories
CREATE UNIQUE INDEX IF NOT EXISTS idx_software_categories_name ON software_categories (name);

-- software_cpe
CREATE INDEX IF NOT EXISTS software_cpe_cpe_idx ON software_cpe (cpe);
CREATE UNIQUE INDEX IF NOT EXISTS unq_software_id ON software_cpe (software_id);

-- software_cve
CREATE INDEX IF NOT EXISTS idx_software_cve_cve ON software_cve (cve);
CREATE UNIQUE INDEX IF NOT EXISTS unq_software_id_cve ON software_cve (software_id, cve);

-- software_host_counts
CREATE INDEX IF NOT EXISTS idx_software_host_counts_team_global_hosts_desc ON software_host_counts (team_id, global_stats, hosts_count DESC, software_id);
CREATE INDEX IF NOT EXISTS idx_software_host_counts_updated_at_software_id ON software_host_counts (updated_at, software_id);

-- software_install_upcoming_activities
CREATE INDEX IF NOT EXISTS fk_software_install_upcoming_activities_policy_id ON software_install_upcoming_activities (policy_id);
CREATE INDEX IF NOT EXISTS fk_software_install_upcoming_activities_software_installer_id ON software_install_upcoming_activities (software_installer_id);
CREATE INDEX IF NOT EXISTS fk_software_install_upcoming_activities_software_title_id ON software_install_upcoming_activities (software_title_id);

-- software_installer_labels
CREATE UNIQUE INDEX IF NOT EXISTS idx_software_installer_labels_software_installer_id_label_id ON software_installer_labels (software_installer_id, label_id);
CREATE INDEX IF NOT EXISTS label_id ON software_installer_labels (label_id);

-- software_installer_software_categories
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_software_installer_id_software_category_id ON software_installer_software_categories (software_installer_id, software_category_id);
CREATE INDEX IF NOT EXISTS software_category_id ON software_installer_software_categories (software_category_id);

-- software_installers
CREATE INDEX IF NOT EXISTS fk_software_installers_fleet_library_app_id ON software_installers (fleet_maintained_app_id);
CREATE INDEX IF NOT EXISTS fk_software_installers_install_script_content_id ON software_installers (install_script_content_id);
CREATE INDEX IF NOT EXISTS fk_software_installers_post_install_script_content_id ON software_installers (post_install_script_content_id);
CREATE INDEX IF NOT EXISTS fk_software_installers_team_id ON software_installers (team_id);
CREATE INDEX IF NOT EXISTS fk_software_installers_title ON software_installers (title_id);
CREATE INDEX IF NOT EXISTS fk_software_installers_user_id ON software_installers (user_id);
CREATE INDEX IF NOT EXISTS fk_uninstall_script_content_id ON software_installers (uninstall_script_content_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_software_installers_team_title_version ON software_installers (global_or_team_id, title_id, version);

-- software_title_display_names
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_team_id_title_id ON software_title_display_names (team_id, software_title_id);
CREATE INDEX IF NOT EXISTS software_title_id ON software_title_display_names (software_title_id);

-- software_title_icons
CREATE INDEX IF NOT EXISTS idx_storage_id_team_id ON software_title_icons (storage_id, team_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_team_id_title_id_storage_id ON software_title_icons (team_id, software_title_id);
CREATE INDEX IF NOT EXISTS software_title_id ON software_title_icons (software_title_id);

-- software_titles
CREATE UNIQUE INDEX IF NOT EXISTS idx_software_titles_bundle_identifier ON software_titles (bundle_identifier, additional_identifier);
CREATE INDEX IF NOT EXISTS idx_sw_titles ON software_titles (name, source, extension_for);
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_sw_titles ON software_titles (unique_identifier, source, extension_for);

-- software_titles_host_counts
CREATE INDEX IF NOT EXISTS idx_software_titles_host_counts_team_global_hosts ON software_titles_host_counts (team_id, global_stats, hosts_count, software_title_id);
CREATE INDEX IF NOT EXISTS idx_software_titles_host_counts_updated_at_software_title_id ON software_titles_host_counts (updated_at, software_title_id);

-- software_update_schedules
CREATE UNIQUE INDEX IF NOT EXISTS idx_team_title ON software_update_schedules (team_id, title_id);
CREATE INDEX IF NOT EXISTS title_id ON software_update_schedules (title_id);

-- teams
CREATE UNIQUE INDEX IF NOT EXISTS idx_name_bin ON teams (name_bin);
CREATE UNIQUE INDEX IF NOT EXISTS idx_teams_filename ON teams (filename);

-- upcoming_activities
CREATE INDEX IF NOT EXISTS fk_upcoming_activities_user_id ON upcoming_activities (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_upcoming_activities_execution_id ON upcoming_activities (execution_id);
CREATE INDEX IF NOT EXISTS idx_upcoming_activities_host_id_activity_type ON upcoming_activities (activity_type, host_id);
CREATE INDEX IF NOT EXISTS idx_upcoming_activities_host_id_priority_created_at ON upcoming_activities (host_id, priority, created_at);

-- user_teams
CREATE INDEX IF NOT EXISTS fk_user_teams_team_id ON user_teams (team_id);

-- users
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_unique_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_name ON users (name);
CREATE UNIQUE INDEX IF NOT EXISTS invite_id ON users (invite_id);

-- verification_tokens
CREATE UNIQUE INDEX IF NOT EXISTS token ON verification_tokens (token);
CREATE INDEX IF NOT EXISTS verification_tokens_users ON verification_tokens (user_id);

-- vpp_app_configurations
CREATE INDEX IF NOT EXISTS fk_vpp_app_configurations_app ON vpp_app_configurations (application_id, platform);
CREATE UNIQUE INDEX IF NOT EXISTS idx_vpp_app_config_team_app_platform ON vpp_app_configurations (team_id, application_id, platform);

-- vpp_app_team_labels
CREATE UNIQUE INDEX IF NOT EXISTS idx_vpp_app_team_labels_vpp_app_team_id_label_id ON vpp_app_team_labels (vpp_app_team_id, label_id);
CREATE INDEX IF NOT EXISTS label_id ON vpp_app_team_labels (label_id);

-- vpp_app_team_software_categories
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_vpp_app_team_id_software_category_id ON vpp_app_team_software_categories (vpp_app_team_id, software_category_id);
CREATE INDEX IF NOT EXISTS software_category_id ON vpp_app_team_software_categories (software_category_id);

-- vpp_app_upcoming_activities
CREATE INDEX IF NOT EXISTS fk_vpp_app_upcoming_activities_adam_id_platform ON vpp_app_upcoming_activities (adam_id, platform);
CREATE INDEX IF NOT EXISTS fk_vpp_app_upcoming_activities_policy_id ON vpp_app_upcoming_activities (policy_id);
CREATE INDEX IF NOT EXISTS fk_vpp_app_upcoming_activities_vpp_token_id ON vpp_app_upcoming_activities (vpp_token_id);

-- vpp_apps
CREATE INDEX IF NOT EXISTS fk_vpp_apps_title ON vpp_apps (title_id);

-- vpp_apps_teams
CREATE INDEX IF NOT EXISTS adam_id ON vpp_apps_teams (adam_id, platform);
CREATE INDEX IF NOT EXISTS fk_vpp_apps_teams_vpp_token_id ON vpp_apps_teams (vpp_token_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_global_or_team_id_adam_id ON vpp_apps_teams (global_or_team_id, adam_id, platform);
CREATE INDEX IF NOT EXISTS team_id ON vpp_apps_teams (team_id);

-- vpp_token_teams
CREATE INDEX IF NOT EXISTS fk_vpp_token_teams_vpp_token_id ON vpp_token_teams (vpp_token_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_vpp_token_teams_team_id ON vpp_token_teams (team_id);

-- vpp_tokens
CREATE UNIQUE INDEX IF NOT EXISTS idx_vpp_tokens_location ON vpp_tokens (location);

-- vulnerability_host_counts
CREATE UNIQUE INDEX IF NOT EXISTS cve_team_id_global_stats ON vulnerability_host_counts (cve, team_id, global_stats);

-- windows_mdm_command_queue
CREATE INDEX IF NOT EXISTS command_uuid ON windows_mdm_command_queue (command_uuid);

-- windows_mdm_command_results
CREATE INDEX IF NOT EXISTS command_uuid ON windows_mdm_command_results (command_uuid);
CREATE INDEX IF NOT EXISTS response_id ON windows_mdm_command_results (response_id);

-- windows_mdm_responses
CREATE INDEX IF NOT EXISTS enrollment_id ON windows_mdm_responses (enrollment_id);

-- yara_rules
CREATE UNIQUE INDEX IF NOT EXISTS idx_yara_rules_name ON yara_rules (name);
