// gen_updated_at_triggers generates the PG trigger set that mirrors MySQL's
// `ON UPDATE CURRENT_TIMESTAMP` column attribute, from the canonical
// schema.sql. MySQL auto-touches such columns on every row-changing UPDATE;
// PG needs a BEFORE UPDATE trigger per table. The original PG baseline was
// pg_dump-derived from tables loaded outside the rebind driver, so only the
// handful of tables created *through* the driver ever got triggers — leaving
// updated_at frozen at insert time on 100+ tables (BitLocker grace periods,
// decryptable-recalc cutoffs, and anything else comparing updated_at
// misbehaved).
//
// Output (server/datastore/mysql/pg_touch_triggers_gen.sql) is embedded and
// executed on every `fleet prepare db` after pg_baseline_post.sql; every
// statement is CREATE OR REPLACE so it is idempotent and converges tables
// that already have the driver-created trigger of the same name.
//
// Run via: go run ./tools/pgcompat/gen_updated_at_triggers
// CI verifies the output is not stale (validate-pg-compat.yml).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"regexp"
	"sort"
)

var (
	reCreateTable = regexp.MustCompile("^CREATE TABLE `(\\w+)` \\(")
	reOnUpdateCol = regexp.MustCompile("^  `(\\w+)`.*ON UPDATE CURRENT_TIMESTAMP")
)

func main() {
	schemaPath := flag.String("schema", "server/datastore/mysql/schema.sql", "path to MySQL schema.sql")
	outPath := flag.String("output", "server/datastore/mysql/pg_touch_triggers_gen.sql", "path to write generated SQL")
	flag.Parse()

	src, err := os.ReadFile(*schemaPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read %s: %v\n", *schemaPath, err)
		os.Exit(1)
	}

	// table → set of ON UPDATE CURRENT_TIMESTAMP columns.
	touch := map[string]map[string]bool{}
	current := ""
	for _, line := range bytes.Split(src, []byte("\n")) {
		if m := reCreateTable.FindSubmatch(line); m != nil {
			current = string(m[1])
			continue
		}
		if current == "" {
			continue
		}
		if m := reOnUpdateCol.FindSubmatch(line); m != nil {
			if touch[current] == nil {
				touch[current] = map[string]bool{}
			}
			touch[current][string(m[1])] = true
		}
	}

	tables := make([]string, 0, len(touch))
	for t := range touch {
		tables = append(tables, t)
	}
	sort.Strings(tables)

	var buf bytes.Buffer
	buf.WriteString(`-- Code generated by tools/pgcompat/gen_updated_at_triggers; DO NOT EDIT.
-- Mirrors every MySQL ON UPDATE CURRENT_TIMESTAMP column attribute as a PG
-- BEFORE UPDATE trigger. Executed on every fleet prepare db, after
-- pg_baseline_post.sql (which defines fleet_set_updated_at). Idempotent.

-- Generic single-column toucher for the few tables whose auto-touch column
-- is not named updated_at (delivered_at / created_at / accessed_at). Mirrors
-- MySQL semantics: touch only when the row actually changed and the column
-- was not explicitly assigned by the statement.
CREATE OR REPLACE FUNCTION public.fleet_touch_column() RETURNS trigger AS $fleet_touch_column$
BEGIN
    IF NEW IS DISTINCT FROM OLD
       AND (to_jsonb(NEW)->TG_ARGV[0]) IS NOT DISTINCT FROM (to_jsonb(OLD)->TG_ARGV[0]) THEN
        NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], CURRENT_TIMESTAMP));
    END IF;
    RETURN NEW;
END $fleet_touch_column$ LANGUAGE plpgsql;

`)
	for _, t := range tables {
		cols := make([]string, 0, len(touch[t]))
		for c := range touch[t] {
			cols = append(cols, c)
		}
		sort.Strings(cols)
		for _, c := range cols {
			if c == "updated_at" {
				fmt.Fprintf(&buf, "CREATE OR REPLACE TRIGGER %s_set_updated_at BEFORE UPDATE ON public.%s FOR EACH ROW EXECUTE FUNCTION public.fleet_set_updated_at();\n", t, t)
			} else {
				fmt.Fprintf(&buf, "CREATE OR REPLACE TRIGGER %s_set_%s BEFORE UPDATE ON public.%s FOR EACH ROW EXECUTE FUNCTION public.fleet_touch_column('%s');\n", t, c, t, c)
			}
		}
	}

	if err := os.WriteFile(*outPath, buf.Bytes(), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", *outPath, err)
		os.Exit(1)
	}
	fmt.Printf("Generated %s: %d tables, %d triggers\n", *outPath, len(tables), countTriggers(touch))
}

func countTriggers(touch map[string]map[string]bool) int {
	n := 0
	for _, cols := range touch {
		n += len(cols)
	}
	return n
}
