// gen_identity_cols extracts every table with a MySQL AUTO_INCREMENT column
// from the canonical schema (server/datastore/mysql/schema.sql) and writes a
// generated Go source file to server/platform/postgres/. The map is consumed
// by the rebind driver to emulate MySQL's LastInsertId() semantics on PG:
// when an INSERT targets a table with an IDENTITY column, the driver rewrites
// the statement to append `RETURNING <col>` and captures the generated value.
//
// Source of truth is schema.sql — NOT the PG baseline — because upstream
// regenerates schema.sql on every migration: a post-baseline migration that
// creates an AUTO_INCREMENT table lands here immediately, whereas the PG
// baseline is only regenerated at rebase time (and a missing entry means the
// driver silently returns LastInsertId()==0, corrupting FK relationships).
//
// Run via: go run ./tools/pgcompat/gen_identity_cols
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
)

var (
	reCreateTable = regexp.MustCompile("^CREATE TABLE `([a-z_][a-z0-9_]*)` \\(")
	// Column line inside a CREATE TABLE block carrying the AUTO_INCREMENT
	// attribute. Table options like `) ENGINE=InnoDB AUTO_INCREMENT=5` start
	// with `)` and don't match.
	reAutoIncCol = regexp.MustCompile("^\\s+`([a-z_][a-z0-9_]*)`\\s.*\\bAUTO_INCREMENT\\b")
)

func main() {
	schemaPath := flag.String("schema", "server/datastore/mysql/schema.sql", "path to MySQL schema.sql")
	outPath := flag.String("output", "server/platform/postgres/schema_identity_cols_gen.go", "path to write generated file")
	flag.Parse()

	f, err := os.Open(*schemaPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "open %s: %v\n", *schemaPath, err)
		os.Exit(1)
	}

	identity := map[string]string{}
	currentTable := ""
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		if m := reCreateTable.FindStringSubmatch(line); m != nil {
			currentTable = m[1]
			continue
		}
		if currentTable == "" {
			continue
		}
		if m := reAutoIncCol.FindStringSubmatch(line); m != nil {
			identity[currentTable] = m[1]
		}
	}
	scanErr := scanner.Err()
	f.Close()
	if scanErr != nil {
		fmt.Fprintf(os.Stderr, "scan: %v\n", scanErr)
		os.Exit(1)
	}

	tables := make([]string, 0, len(identity))
	for t := range identity {
		tables = append(tables, t)
	}
	sort.Strings(tables)

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by tools/pgcompat/gen_identity_cols; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package postgres\n\n")
	fmt.Fprintf(&buf, "// schemaIdentityCols maps each table that owns an IDENTITY column in the\n")
	fmt.Fprintf(&buf, "// embedded PG baseline (pg_baseline_schema.sql) to that column's name.\n")
	fmt.Fprintf(&buf, "// rebind_driver.go uses this map to emulate MySQL LastInsertId() on PG by\n")
	fmt.Fprintf(&buf, "// appending RETURNING <col> to INSERT statements and capturing the value.\n")
	fmt.Fprintf(&buf, "// Regenerate with: go run ./tools/pgcompat/gen_identity_cols\n")
	fmt.Fprintf(&buf, "var schemaIdentityCols = map[string]string{\n")
	for _, t := range tables {
		fmt.Fprintf(&buf, "\t%q: %q,\n", t, identity[t])
	}
	fmt.Fprintf(&buf, "}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(*outPath, src, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", *outPath, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s with %d IDENTITY-bearing tables\n", *outPath, len(tables))
}
