// gen_identity_cols extracts every table that has an IDENTITY column in the
// Fleet PG baseline schema and writes a generated Go source file to
// server/platform/postgres/. The map is consumed by the rebind driver to
// emulate MySQL's LastInsertId() semantics on PG: when an INSERT targets a
// table with an IDENTITY column, the driver rewrites the statement to append
// `RETURNING <col>` and captures the generated value.
//
// Run via: go run ./tools/pgcompat/gen_identity_cols
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
)

// Matches both `GENERATED ALWAYS AS IDENTITY` and `GENERATED BY DEFAULT AS IDENTITY`.
// pg_dump emits these as ALTER TABLE statements after the CREATE TABLE.
var reIdentity = regexp.MustCompile(
	`^ALTER TABLE (?:ONLY )?(?:public\.)?([a-z_][a-z0-9_]*)\s+ALTER COLUMN\s+([a-z_][a-z0-9_]*)\s+ADD GENERATED\b`)

func main() {
	schemaPath := flag.String("schema", "server/datastore/mysql/pg_baseline_schema.sql", "path to PG baseline schema")
	outPath := flag.String("output", "server/platform/postgres/schema_identity_cols_gen.go", "path to write generated file")
	flag.Parse()

	f, err := os.Open(*schemaPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "open %s: %v\n", *schemaPath, err)
		os.Exit(1)
	}

	identity := map[string]string{}
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		if m := reIdentity.FindStringSubmatch(scanner.Text()); m != nil {
			identity[m[1]] = m[2]
		}
	}
	scanErr := scanner.Err()
	f.Close()
	if scanErr != nil {
		fmt.Fprintf(os.Stderr, "scan: %v\n", scanErr)
		os.Exit(1)
	}

	tables := make([]string, 0, len(identity))
	for t := range identity {
		tables = append(tables, t)
	}
	sort.Strings(tables)

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by tools/pgcompat/gen_identity_cols; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package postgres\n\n")
	fmt.Fprintf(&buf, "// schemaIdentityCols maps each table that owns an IDENTITY column in the\n")
	fmt.Fprintf(&buf, "// embedded PG baseline (pg_baseline_schema.sql) to that column's name.\n")
	fmt.Fprintf(&buf, "// rebind_driver.go uses this map to emulate MySQL LastInsertId() on PG by\n")
	fmt.Fprintf(&buf, "// appending RETURNING <col> to INSERT statements and capturing the value.\n")
	fmt.Fprintf(&buf, "// Regenerate with: go run ./tools/pgcompat/gen_identity_cols\n")
	fmt.Fprintf(&buf, "var schemaIdentityCols = map[string]string{\n")
	for _, t := range tables {
		fmt.Fprintf(&buf, "\t%q: %q,\n", t, identity[t])
	}
	fmt.Fprintf(&buf, "}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(*outPath, src, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", *outPath, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s with %d IDENTITY-bearing tables\n", *outPath, len(tables))
}
